service: zappy-ride

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-1
  profile: zappy

functions:
  events:
    handler: handler.handler
    events:
      - http:
          path: events
          method: get
      - http:
          path: events
          method: post
      - http:
          path: events
          method: delete
      - http:
          path: events
          method: put

package:
    include:
      - .dist/**