service: zappy-ride

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

functions:
  events:
    handler: handler.hello
    events:
      - http:
          path: events
          method: get
      - http:
          path: events
          method: post
      - http:
          path: events
          method: delete
      - http:
          path: events
          method: put
